// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1Gd2JG9Uj1MqSPhGHEerkpdUpBE2uTE',
    appId: '1:1029128192487:web:bdc72e767218b3588b3d42',
    messagingSenderId: '1029128192487',
    projectId: 'medassist-e6135',
    authDomain: 'medassist-e6135.firebaseapp.com',
    storageBucket: 'medassist-e6135.firebasestorage.app',
    measurementId: 'G-MCDLDGDTF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMsqah7u4BuZb0lviaSDZdFwVEJWXl3a8',
    appId: '1:1029128192487:android:66a68681a5bcdc428b3d42',
    messagingSenderId: '1029128192487',
    projectId: 'medassist-e6135',
    storageBucket: 'medassist-e6135.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7-Xmzty7L4niwh5wZ1p1B_vycm7kYkEk',
    appId: '1:1029128192487:ios:617ce257ca5450dc8b3d42',
    messagingSenderId: '1029128192487',
    projectId: 'medassist-e6135',
    storageBucket: 'medassist-e6135.firebasestorage.app',
    iosBundleId: 'com.example.uniapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7-Xmzty7L4niwh5wZ1p1B_vycm7kYkEk',
    appId: '1:1029128192487:ios:617ce257ca5450dc8b3d42',
    messagingSenderId: '1029128192487',
    projectId: 'medassist-e6135',
    storageBucket: 'medassist-e6135.firebasestorage.app',
    iosBundleId: 'com.example.uniapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk1Gd2JG9Uj1MqSPhGHEerkpdUpBE2uTE',
    appId: '1:1029128192487:web:77053f061f8df8048b3d42',
    messagingSenderId: '1029128192487',
    projectId: 'medassist-e6135',
    authDomain: 'medassist-e6135.firebaseapp.com',
    storageBucket: 'medassist-e6135.firebasestorage.app',
    measurementId: 'G-H09DZR5H6M',
  );
}
